# Generated by Django 5.0.1 on 2024-01-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='times_used',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Рецепт'),
        ),
    ]
