# Generated by Django 5.0.1 on 2024-01-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_name_alter_product_times_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='times_used',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
